plugins {
    id 'java-library'
}

group = 'com.cb-doctor'
version = rootProject.version

dependencies {
    implementation project(":utilities")

    // HTTP
    implementation "com.squareup.okhttp3:okhttp:5.3.2"

    // JSON (central versioning with BOM)
    implementation platform("com.fasterxml.jackson:jackson-bom:2.20.1")
    implementation "com.fasterxml.jackson.core:jackson-databind"

    // Logging API
    api "org.slf4j:slf4j-api:2.0.17"

    testImplementation "org.junit.jupiter:junit-jupiter"
    testImplementation "com.squareup.okhttp3:mockwebserver3:5.3.2"

    testRuntimeOnly "ch.qos.logback:logback-classic:1.5.18"
}
